spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reddit_clone_db
    username: codingstreams
    password: CS$2196

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api

jwt:
  secret: jgbbvovujedstyvdytvoudbghullgeir
  expiration: 604800000
